Revert "Change 'OEM' to 'Service Provider' in hippa_admin.feature (Mozy-120085); Popup an RuntimeError with message instead of undefined method 'upcase' for nil:NilClass (NoMethodError"
This reverts commit bb73f6f8d8a265a4b1a2f97a2cfd63a85ea30e6b.

Change-Id: I65dcf1e9f779c0914fa53900ccb72b4d5edd3f32
Reviewed-on: https://gerrit.dechocorp.com/75232
Reviewed-by: Catherine Liao <catherinel@mozy.com>