Change 'OEM' to 'Service Provider' in hippa_admin.feature (Mozy-120085); Popup an RuntimeError with message instead of undefined method 'upcase' for nil:NilClass (NoMethodError
Change-Id: Iafb51553a8073b15451e85267d2f0b15785df20a
Reviewed-on: https://gerrit.dechocorp.com/75187
Reviewed-by: Catherine Liao <catherinel@mozy.com>